services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  employee-service:
    container_name: employee-service1
    image: debayanc/employee-service:with-mysql-db
    environment:
      - 'DB_SERVER=mysql'
      - 'DB_PORT=3306'
      - 'DB_DATABASENAME=mydatabase'
      - 'DB_PASSWORD=secret'
      - 'DB_USERNAME=myuser'
    ports:
      - '8080:8080'