apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-prod
  labels:
    app: employee-service
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: employee-service
    tier: backend