apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    tier: database
spec:
  ports:
    - port: 3306
      name: mysql
  selector:
    app: {{ .Chart.Name }}
    tier: database
  clusterIP: None