apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    tier: database
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc }}
  mysql-user-password: {{ .Values.mysql.userPassword | b64enc }}