apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: employee-prod

namePrefix: prod-

commonLabels:
  environment: production

patches:
- path: resource-limits.yaml
  target:
    kind: Deployment
    name: base-employee-service
- path: replica-count.yaml
  target:
    kind: Deployment
    name: base-employee-service

replicas:
- name: base-employee-service
  count: 3