apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-employee-service
spec:
  template:
    spec:
      containers:
      - name: employee-service
        resources:
          requests:
            cpu: '0.2'
            memory: "400Mi"
          limits:
            cpu: '0.5'
            memory: "800Mi"