apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    env: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      env: sandbox
  template:
    metadata:
      labels:
        env: sandbox
    spec:
      containers:
      - name:  employee-service
        image: debayanc/employee-service:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '0.2'
            memory: "600Mi"
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 20
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name:  mysql-config-map
              key: mysql-server
        - name: DB_DATABASENAME
          valueFrom:
            configMapKeyRef:
              name:  mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-user-username
        - name: DB_PORT
          value: '3306'
