apiVersion: v1
kind: Service
metadata:
  name: employee-service-mysql
  labels:
    app: employee-service
spec:
  ports:
    - port: 3306
  selector:
    app: employee-service
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: employee-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-mysql
  labels:
    app: employee-service
spec:
  selector:
    matchLabels:
      app: employee-service
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: employee-service
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        resources:
          limits:
            cpu: '0.2'
            memory: "1Gi"
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-database-name
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-user-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-user-password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc